#version: '3.9'

services:
  db:
    build: ./pg
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pg/data:/var/lib/postgresql/data
    #  - ./pg_data/init:/docker-entrypoint-initdb.d
    #  - /etc/postgresql:/etc/postgresql
    networks:
      - internal
    ports:
      - "5434:5432"
    #  - "2222:22"

  nextjs:
    build: ./firmahaku
    restart: always
    container_name: nextjs-web
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_USER}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    networks:
      - internal
    ports:
      - "3001:3000"
    depends_on:
      - db
    # commented because it copies the source code to the container in dockerfile
    #volumes:    
    #
    #  - ./firmahaku:/home/apps/firma/firmahaku

networks:
  internal: 
    driver: bridge