name: Deploy to Production

on:
  push:
    branches: [master]
  workflow_dispatch: # allows manual run from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update OpenSSH client
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client rsync

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.PROD_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -p 20203 -H ${{ secrets.PROD_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Copy project to server
      run: |
        rsync -az -e "ssh -p 20203" --delete --exclude='.env'  ./ ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:${{ secrets.DEPLOY_DIR }}

    - name: Deploy with Docker Compose
      run: |
        ssh -p 20203 ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} << 'EOF'
          cd ${{ secrets.DEPLOY_DIR }}
          docker compose down
          docker compose up -d --build
        EOF
